export const FETCH_BRANDS_SUCCESS = "FETCH_BRANDS_SUCCESS";
export const FETCH_COLORS_SUCCESS = "FETCH_COLORS_SUCCESS";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_SIZES_SUCCESS = "FETCH_SIZES_SUCCESS";
export const FETCH_GENDER_SUCCESS = "FETCH_GENDER_SUCCESS";
export const FETCH_FILTERED_PRODUCTS_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_FILTERED_PRODUCTS_FAILURE =
  "FETCH_CATEGORY_FaFETCH_FILTERED_PRODUCTS_FAILURE";
export const SET_FILTERED_PRODUCTS = "SET_FILTERED_PRODUCTS";
