// favoriteTypes.js

export const ADD_TO_FAVORITES_SUCCESS = "ADD_TO_FAVORITES";
export const ADD_TO_FAVORITES_FAILURE = "ADD_TO_CART_FAILURE";
export const LOAD_FAVORITES_SUCCESS = "LOAD_FAVORITES_SUCCESS";
export const LOAD_FAVORITES_FAILURE = "LOAD_FAVORITES_FAILURE";
export const REMOVE_FROM_FAVORITES_SUCCESS = "REMOVE_FROM_FAVORITES_SUCCESS";
export const REMOVE_FROM_FAVORITES_FAILURE = "REMOVE_FROM_FAVORITES_FAILURE";
