export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";
export const SELECT_IMAGE = "SELECT_IMAGE";
export const SELECT_SIZE = "SELECT_SIZE";
export const SELECT_COLOR = "SELECT_COLOR";
export const SELECT_PRODUCT_CHILDREN_ID = "SELECT_PRODUCT_CHILDREN_ID";
// search
export const SEARCH_PRODUCTS_REQUEST = "SEARCH_PRODUCTS_REQUEST";
export const SEARCH_PRODUCTS_SUCCESS = "SEARCH_PRODUCTS_SUCCESS";
export const SEARCH_PRODUCTS_FAILURE = "SEARCH_PRODUCTS_FAILURE";

        